### ISSUE TITLE
Error in if (rat < 0) { : the condition has length > 1

### ISSUE THREAD

**Issue by POTCHARAARIYA** [cran/soilassessment#1]
Hi,

predictors$CRSI=imageIndices(predictors$BBlue,predictors$BGreen,predictors$BRed,predictors$BIRed,predictors$swir1,predictors$swir2,"CRSI");summary(predictors$CRSI)
Error in if (rat < 0) { : the condition has length > 1

I have a CRSI specific problem, but the others have no problem.

what should I do?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by POTCHARAARIYA** [comment]
Thanks

ในวันที่ จ. 19 ก.ย. 2022 เวลา 21:14 Gábor Csárdi ***@***.***>
เขียนว่า:
